[package]
name = "saleor-app-sdk"
authors = ["Djkáťo <djkatovfx@gmail.com>"]
version = "0.1.2"
edition = "2021"
description = "Unofficial Saleor App SDK like library, made to for Rust."
keywords = ["saleor", "sdk", "plugin"]
categories = ["api-bindings", "web-programming::http-server"]
homepage = "https://github.com/djkato/saleor-apps-rs"
repository = "https://github.com/djkato/saleor-apps-rs"
documentation = "https://github.com/djkato/saleor-apps-rs"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow.workspace = true
redis = { workspace = true, features = [
  "aio",
  "tokio-comp",
  "connection-manager",
] }
serde.workspace = true
axum.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
envy.workspace = true
dotenvy.workspace = true
tower = { workspace = true }
rust_decimal = { workspace = true, features = ["serde-float"] }
reqwest = { version = "0.11.24", features = ["json"] }
jsonwebtoken = "9.2.0"
async-trait = "0.1.77"
http = "1.0.0"
url = "2.5.0"
strum = "0.26.0"
strum_macros = "0.26.1"
