name: clippy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: clippy
        run: cargo +nightly clippy --all-features -- -Dwarnings
        continue-on-error: false
